// flow-typed signature: abe01c5aea90cc1b97f393bb9580149d
// flow-typed version: <<STUB>>/next-redux-wrapper_vx.x.x/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redux-wrapper' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-redux-wrapper/src/index' {
  declare module.exports: any
}

declare module 'next-redux-wrapper/src/index.server.spec' {
  declare module.exports: any
}

declare module 'next-redux-wrapper/src/index.spec' {
  declare module.exports: any
}

// Filename aliases
declare module 'next-redux-wrapper/src/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index'>
}
declare module 'next-redux-wrapper/src/index.server.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index.server.spec'>
}
declare module 'next-redux-wrapper/src/index.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index.spec'>
}
